[build]
  command = "npm install && npm run build && npm run start"
  publish = "./"

[functions.api]
  handler = "node app.js"
  included_files = ["app.js", "package.json"]

[[redirects]]
  from = "/api/*"
  to = "https://beapro.pro/public/index.html/:splat"
  status = 200
  force = true
